### ISSUE TITLE
NoClassDefFoundError when clicking "choose" in LocalWorkerSettings Control

### ISSUE THREAD

**Issue by b-01** [Nuix/Nx#5]
I have a custom script that uses a TabbedCustomDialog and in it, I added a local worker settings control.

Whenever i click on "choose" in this control, i get a NoClassDefFoundError.
Script worked fine till around 8.2ish.

Sample code (script is in python):
```python   dialog = TabbedCustomDialog()
    tab = dialog.addTab("tab_tags", "Tags")
    tab.appendChoiceTable("selected_tags", "Tags", all_tags)
    tab.appendSeparator("Worker Settings")
    tab.appendLocalWorkerSettings("worker_settings")
```

Stack Trace:
```
Unexpected Error
 
Message:
com/nuix/nx/dialogs/CommonDialogs
Stack Trace:
java.lang.NoClassDefFoundError: com/nuix/nx/dialogs/CommonDialogs
	at com.nuix.nx.controls.PathSelectionControl$1.actionPerformed(PathSelectionControl.java:73)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by JuicyDragon** [comment]
Hello @b-01 this is a rather odd error.  When you click on the button to select a temp directory in that control it goes to this code:

https://github.com/Nuix/Nx/blob/master/Java/src/main/java/com/nuix/nx/controls/PathSelectionControl.java#L70-L75

The [CommonDialogs](https://github.com/Nuix/Nx/blob/master/Java/src/main/java/com/nuix/nx/dialogs/CommonDialogs.java) class that the stack trace states is missing has been present in Nx basically since the beginning.

I tested locally with the latest jar and didn't have the problem on my end.  Here are somethings we can look at initially:
- Are you running with a version of the Nx.jar you compiled locally or are you using a release version you downloaded here from GitHub?
- Try [downloading the latest release](https://github.com/Nuix/Nx/releases) of the jar file and make sure that is the one you are using with your script.
- Check to see if there is possibly a second copy of the Nx.jar file in the `lib` sub-directory of your Nuix install (for example `C:\Program Files\Nuix\Nuix 8.2\lib\Nx.jar`).  Nuix adds the jars in this directory to the class path on startup and I have run into instances where someone has placed an older version of the jar file there and it causes weird conflicts with newer versions of the jar that a script may be using.

**Comment by JuicyDragon** [comment]
Closing due to inactivity
